spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  show-sql: true
org:
  jobrunr:
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
    dashboard:
      port: 8000
      enabled: true